Repository swamimalode07/SimonsaysGame, pull requests merged in 2024-10, with the labels that each got.

#14 🚀 Updated Login Page Ui
  views/login.ejs
Labels: enhancement, hacktoberfest

#23 Fixes - #5 Bug Impacting Game Credibility
  views/main.ejs
Labels: bug, hacktoberfest

#22 Fixes #18 : Added Useful Comments And Improved Code Readability
  app.cjs
Labels: hacktoberfest

#6 Fixing issue #1
  .gitignore
  README.md
  public/styletwo.css
  views/main.ejs
Labels: enhancement, hacktoberfest

#33 Added "Back to top" button issue
  views/leaderboard.ejs
Labels: enhancement, good first issue, hacktoberfest

#37 Revert "Added "Back to top" button issue"
  views/leaderboard.ejs
Labels: bug, hacktoberfest

#38 adding play again button
  .gitignore
  views/leaderboard.ejs
  views/main.ejs
Labels: enhancement, hacktoberfest

#41 Revert "adding play again button"
  .gitignore
  views/leaderboard.ejs
  views/main.ejs
Labels: good first issue, hacktoberfest

#47 Revert "Added Pagination for the leaderboard #34"
  views/leaderboard.ejs
Labels: bug, hacktoberfest

#58 Revert "Done with search functionality #2"
  app.cjs
  public/leaderboard.css
  views/leaderboard.ejs
Labels: bug, hacktoberfest, hacktoberfest-accepted

#64 Improve the UI of "How to play btn"
  views/main.ejs
Labels: bug, enhancement, hacktoberfest-accepted
